version: "3.7"

services:
  prometheus:
    build: ./prometheus
    image: prom/prometheus:v2.3.1
    ports: 
      - "9090:9090"
    networks: 
      - monit-network
    volumes: 
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    expose: 
      - 9090
    healthcheck:
      test: ["CMD", "wget", "http://localhost:9090"]
      interval: 10s
      timeout: 15s
      retries: 10
      start_period: 40s            


  grafana:
    build: ./grafana
    image: grafana-customized
    ports:
      - "3000:3000"
    networks:
      - monit-network
    depends_on: 
      prometheus:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 40s              

networks: 
  monit-network:

volumes:
  jenkins-data:  




