{
 "title": "Avladu-Windows Host Metrics DEV",
 "description": "Basic overview of windows host metrics, based on windows Exporter (v0.19.0)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(windows_os_time, job)"
    }
   },
   {
    "name": "host",
    "label": "Hostname",
    "query": {
     "query": "label_values(windows_os_time{job=~\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_time{instance=~\"$host\"} - windows_system_system_up_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 3, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 5, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(windows_hyperv_vm_cpu_total_run_time{instance=~\"$host.*\"}[2m])) by (instance) / sum(windows_cs_logical_processors{instance=~\"$host.*\"}) by (instance) / 10000000) + (100 - (avg by (instance) (rate(windows_cpu_time_total{instance=~\"$host.*\", mode=\"idle\"}[100s])) * 100))/100"
    }
   ]
  },
  {
   "title": "Hyper-V CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(windows_hyperv_vm_cpu_total_run_time{instance=~\"$host.*\"}[2m])) by (instance) / sum(windows_cs_logical_processors{instance=~\"$host.*\"}) by (instance) / 10000000"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_os_physical_memory_free_bytes{instance=~\"$host\"} / windows_cs_physical_memory_bytes{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(windows_logical_disk_free_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$host\",volume=~\"^[A-Z]:.*$\"})) > 0"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=~\"$host\"}[24h]))"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Hyper-V CPU Load | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "(sum by (vm) (irate(windows_hyperv_vm_cpu_total_run_time{instance=~\"$host\"}[100s])))/10000000",
     "legendFormat": "{{vm}}"
    }
   ]
  },
  {
   "title": "Hyper-V VM | $host",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "repeat": "host",
   "targets": [
    {
     "expr": "windows_hyperv_health_ok {instance=~\"$host\"}",
     "legendFormat": "VM"
    }
   ]
  },
  {
   "title": "System Threads | $host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{instance=~\"$host\"}",
     "legendFormat": "threads"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory | $host",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$host\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "(windows_cs_physical_memory_bytes{instance=~\"$host\"} - windows_os_physical_memory_free_bytes{instance=~\"$host\"})",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Network Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Traffic | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "irate(windows_net_bytes_received_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) > 0",
       "legendFormat": "Received"
      },
      {
       "expr": "- irate(windows_net_bytes_sent_total{instance=~\"$host\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) < 0",
       "legendFormat": "Sent"
      }
     ]
    },
    {
     "title": "Network discarded/error | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
     "repeat": "host",
     "yaxes": [
      { "format": "pps", "label": "Load" }
     ],
     "targets": [
      {
       "expr": "irate(windows_net_packets_outbound_discarded{instance=~\"$host\",nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{instance=~\"$host\"}[5m])",
       "legendFormat": "Sent ({{nic}})"
      },
      {
       "expr": "irate(windows_net_packets_received_discarded{instance=~\"$host\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{instance=~\"$host\"}[5m])",
       "legendFormat": "Received ({{nic}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk (Free) | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 49 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "windows_logical_disk_free_bytes{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
       "legendFormat": "{{volume}}"
      }
     ]
    },
    {
     "title": "Disk Activity | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 49 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(windows_logical_disk_write_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    },
    {
     "title": "Disk IO | $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 49 },
     "repeat": "host",
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "- irate(windows_logical_disk_write_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
       "legendFormat": "Write {{volume}}"
      },
      {
       "expr": "irate(windows_logical_disk_read_seconds_total{instance=~\"$host\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
       "legendFormat": "Read {{volume}}"
      }
     ]
    }
   ]
  }
 ]
}